# vim: set ft=yaml :
#
# https://taskfile.dev


version: '3'

set: ['errexit', 'nounset', 'pipefail']

# https://changit.bwh.harvard.edu/nhlmi/manselmi-toybox/tree/main/local/Users/nhlmi/.taskfiles
includes:

  uv:
    taskfile: '{{ env "TASKFILE_INCLUDES_ROOT_DIR" }}/uv'
    vars:
      PYTHON_MINOR_VERSION: '3.12'
