# vim: set ft=yaml :
#
# https://taskfile.dev


version: '3'

set: ['errexit', 'nounset', 'pipefail']

includes:

  # https://changit.bwh.harvard.edu/nhlmi/manselmi-toybox/tree/main/local/Users/nhlmi/.taskfile/include/uv
  uv:
    taskfile: '{{ env "TASKFILE_INCLUDE_ROOT_DIR" }}/uv'
    vars:
      PYTHON_MINOR_VERSION: '3.12'
